version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install Django psycopg2-binary
      - run:
          name: Run tests
          command: |
            python manage.py migrate
            python manage.py test

  build_docker_image:
    docker:
      - image: circleci/python:3.9
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t my-django-app .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u vatsal929 --password-stdin
            docker tag my-django-app vatsal929/my-django-app:latest
            docker push vatsal929/my-django-app:latest

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dTbd7DeoUsp6E6cpOm1sufbJLEs3Hnglp4PTX+/2vBc"
      - run:
          name: Install docker-compose
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@13.201.94.21 '
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
              sudo chmod +x /usr/local/bin/docker-compose
            '
      - run:
          name: Deploy application
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@13.201.94.21 '
              cd /var/www/html/python &&
              if [ -f docker-compose.yml ]; then
                docker-compose pull &&
                docker-compose up -d
              else
                echo "docker-compose.yml not found!"
                exit 1
              fi
            '

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
      - deploy:
          requires:
            - build_docker_image
