version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install Django psycopg2-binary  # Add your dependencies here
      - run:
          name: Run tests
          command: |
            python manage.py migrate
            python manage.py test

  build_docker_image:
    docker:
      - image: circleci/python:3.9
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t my-django-app .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u vatsal929 --password-stdin
            docker tag my-django-app vatsal929/my-django-app:latest
            docker push vatsal929/my-django-app:latest

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dTbd7DeoUsp6E6cpOm1sufbJLEs3Hnglp4PTX+/2vBc"
      - run:
          name: Install PM2
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@13.201.94.21 'npm install pm2 -g'
      - run:
          name: Deploy application with PM2
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@13.201.94.21 '
              cd /var/www/html/python &&
              pm2 stop my-django-app || true &&
              git pull &&
              pip install -r requirements.txt &&
              python manage.py migrate &&
              pm2 start python --name my-django-app -- manage.py runserver 0.0.0.0:8001
            '

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
      - deploy:
          requires:
            - build_docker_image
